env:
  node: true
  commonjs: true
  es6: true
parser: babel-eslint
extends:
  - airbnb-base
  - plugin:prettier/recommended
globals:
  riot: true
settings:
  import/resolver:
    node: 
      extensions: 
        - .tag
